package com.agentguard.entity;

public enum AuditEventType { USER_CREATED, POLICY_CREATED, TRANSACTION_CREATED, POLICY_EVALUATED, TRANSACTION_APPROVED, TRANSACTION_BLOCKED, TRANSACTION_MANUAL_REVIEW, PAYMENT_CREATED, PAYMENT_FAILED, PAYMENT_COMPLETED }
